export const ON_FIRSTNAME_CHANGED= 'ON_REGISTER_CHANGED';
export const ON_LASTNAME_CHANGED= 'ON_LASTNAME_CHANGED';
export const ON_EMAIL_CHANGED= 'ON_EMAIL_CHANGED';
export const ON_PHONE_CHANGED= 'ON_PHONE_CHANGED';
export const ON_PASSWORD_CHANGED= 'ON_PASSWORD_CHANGED';
export const ON_RETYPE_PASSWORD_CHANGED= 'ON_RETYPE_PASSWORD_CHANGED';

export const ON_LOGIN_EMAIL_CHANGED='ON_LOGIN_EMAIL_CHANGED';
export const ON_LOGIN_PASSWORD_CHANGED='ON_LOGIN_PASSWORD_CHANGED';